version: '3.7'

services:
  nuxt:
    restart: always
    image: finizco/nginx-node:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_PORT=3000
      - NODE_MODE=dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
